export const CategoriesColors = {
  "Self-Help": "bg-yellow-500 hover:bg-yellow-600",
  "Fiction": "bg-blue-500 hover:bg-blue-600",
  "Business": "bg-green-500 hover:bg-green-600",
  "Technology": "bg-red-500 hover:bg-red-600",
  "Science": "bg-purple-500 hover:bg-purple-600",
  "Art": "bg-pink-500 hover:bg-pink-600",
  "Biography": "bg-purple-500 hover:bg-purple-600",
  "History": "bg-gray-500 hover:bg-gray-600",
  "Travel": "bg-green-500 hover:bg-green-600",
  "Religion": "bg-red-500 hover:bg-red-600",
  "Cooking": "bg-purple-500 hover:bg-purple-600",
  "Sports": "bg-pink-500 hover:bg-pink-600",
  "Education": "bg-indigo-500 hover:bg-indigo-600",
  "Comics": "bg-gray-500 hover:bg-gray-600",
  "Behavior modification": "bg-yellow-500 hover:bg-yellow-600",
  "Psychology": "bg-green-500 hover:bg-green-600",
  "FAMILY": "bg-purple-500 hover:bg-purple-600",
  "RELATIONSHIPS": "bg-purple-500 hover:bg-purple-600",
  "Wars": "bg-pink-500 hover:bg-pink-600",
  "World War II": "bg-indigo-500 hover:bg-indigo-600",
  "General": "bg-gray-500 hover:bg-gray-600",
  "Autobiography": "bg-yellow-500 hover:bg-yellow-600",
  "Political": "bg-green-500 hover:bg-green-600",
  "Health": "bg-green-500 hover:bg-green-600",
  "Fitness": "bg-red-500 hover:bg-red-600",
  "Vitamins": "bg-purple-500 hover:bg-purple-600",
  "Diet": "bg-pink-500 hover:bg-pink-600",
  "Nutrition": "bg-indigo-500 hover:bg-indigo-600",
};

export enum Category {
  FICTION = "fiction",
  BUSINESS = "business",
  HISTORY = "history",
  SCIENCE = "science",
  ART = "art",
  BIOGRAPHY = "biography",
  COOKING = "cooking",
  TRAVEL = "travel",
  HEALTH = "health",
  FAMILY = "family",
  SPORTS = "sports",
  RELIGION = "religion",
  PHILOSOPHY = "philosophy",
  PSYCHOLOGY = "psychology",
  EDUCATION = "education",
  LAW = "law",
  COMPUTER = "computer",
  TECHNOLOGY = "technology",
  ENGINEERING = "engineering",
  MATHEMATICS = "mathematics",
  MEDICAL = "medical",
  SOCIAL = "social",
  POLITICAL = "political",
  LITERARY = "literary",
  CRITICISM = "criticism",
  DRAMA = "drama",
  POETRY = "poetry",
}
