/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AUNgNbEjDZy
 */
import Link from "next/link";

export default function NotFound() {
  return (
    <div className="flex items-center justify-center w-full min-h-[400px]">
      <div className="container flex flex-col items-center gap-2 px-4 py-12 text-center md:gap-4 md:px-6">
        <div className="space-y-2">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl lg:text-5xl/none">
            404 Page Not Found
          </h1>
          <p className="text-gray-500 md:text-xl dark:text-gray-400">
            Sorry, we couldn&apos;t find the page you&apos;re looking for.
          </p>
        </div>
        <Link
          className="inline-flex items-center rounded-md border border-gray-200 bg-white px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300"
          href="/"
        >
          Return to website
        </Link>
      </div>
    </div>
  );
}
