/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AUNgNbEjDZy
 * and modified by Faris.
 */

import Link from "next/link";

export default function NotFound() {
  return (
    <div className="flex items-center justify-center w-full h-full">
      <div className="container flex flex-col items-center gap-x-2 gap-y-4 px-4 py-12 text-center">
        <div className="space-y-2">
          <h1 className="text-3xl text-rose-500 font-bold tracking-tighter sm:text-4xl lg:text-5xl/none">
            404 Page Not Found
          </h1>
          <p className="text-gray-500 md:text-xl dark:text-gray-400">
            Sorry, we couldn&apos;t find the page you&apos;re looking for.
          </p>
        </div>

        <div className="relative group rounded-lg p-px text-sm/6 text-zinc-400">
          <span className="absolute  inset-0 overflow-hidden rounded-lg">
            <span className="absolute inset-0 rounded-lg bg-[image:radial-gradient(75%_100%_at_50%_50%,rgba(253,95,120,0.6)_0%,rgba(253,95,120,0)_75%)] opacity-100 animate-ping group-hover:animate-none" />
          </span>
          <Link
            className="relative flex items-center justify-center gap-x-2 z-10 rounded-lg bg-zinc-950 px-4 py-1.5 ring-1 ring-white/10
            transition-all duration-500"
            href="/"
          >
            <div className="group-hover:text-transparent group-hover:bg-clip-text group-hover:bg-gradient-to-br from-zinc-500 via-white to-zinc-500 text-lg font-semibold">
              Get me out of here
            </div>
          </Link>
        </div>
      </div>
    </div>
  );
}
